# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore fiap_hacka.csproj
    - name: Build
      run: dotnet build fiap_hacka.csproj --no-restore
    - name: Restore dependencies Test
      run: dotnet restore ".\xunit.hackfiap.br\xunit.hackfiap.csproj"
    - name: BuildTest
      run: dotnet build ".\xunit.hackfiap.br\xunit.hackfiap.csproj" --no-restore
    - name: Test
      run: dotnet test ".\xunit.hackfiap.br\xunit.hackfiap.csproj" --no-build --verbosity normal
